### ISSUE TITLE
usrp_source.cc:105: reading bad data ?

### ISSUE THREAD

**Issue by dcb314** [steve-m/kalibrate-rtl#11]
usrp_source.cc:105:37: warning: variable 'decimation_f' is uninitialized when used here [-Wuninitialized]

    float decimation_f;

//  decimation_f = (float)m_u_rx->fpga_master_clock_freq() / m_desired_sample_rate;
    m_decimation = (unsigned int)round(decimation_f) & ~1;

**Comment by steve-m** [comment]
That function is dead code (it was only used for the USRP) and doesn't even get called.

**Comment by dcb314** [comment]
>That function is dead code (it was only used for the USRP) and doesn't even get called.

Suggest delete, then.
