### ISSUE TITLE
Installing Ubuntu 16.04

### ISSUE THREAD

**Issue by LibertyUnix** [steve-m/kalibrate-rtl#15]
When running ./configure I get the following error:

./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for working strtod... yes
checking for floor... no
checking for getpagesize... yes
checking for memset... yes
checking for sqrt... no
checking for strtoul... yes
checking for strtol... yes
./configure: line 5097: syntax error near unexpected token `FFTW3,'
./configure: line 5097: `PKG_CHECK_MODULES(FFTW3, fftw3 >= 3.0)'

I have confirmed fftw3 is installed.

**Comment by pvint** [comment]
I had this on my Raspberry Pi too, fixed with:
`apt-get install  libfftw3-dev`

**Comment by kwiki74** [comment]
Hello.
I've try to install it on  raspbian and i have the same issue. 
apt-get install libfftw3-dev doesn't seems fix it for me : 

...
checking for sqrt... no
checking for strtoul... yes
checking for strtol... yes
./configure: line 5083: syntax error near unexpected token `FFTW3,'
./configure: line 5083: `PKG_CHECK_MODULES(FFTW3, fftw3 >= 3.0)'

**Comment by zhiyao** [comment]
Do these steps again
```
sudo apt-get install pkg-config
./bootstrap
./configure
```
